Improve the getting-started docs
vmware-tanzu/cluster-api-provider-bringyourownhost pull request #239
Opened 2021-11-12 04:41 UTC by jamiemonserrate

So that folks don't have to keep jumping between local-development guide

2021-11-12 06:49 UTC, anusha94 reviewed
minor nits. LGTM

2021-11-12 06:49 UTC, anusha94 commented on docs/getting_started.md
> +Once the management cluster is ready, you will need to create a few hosts that that the BringYourOwnHost provider can use, before you can create your first workload cluster.
```suggestion
Once the management cluster is ready, you will need to create a few hosts that the `BringYourOwnHost` provider can use, before you can create your first workload cluster.
```

2021-11-12 06:49 UTC, anusha94 commented on docs/getting_started.md
> +If not, you could create containers to deploy you workload clusters on. We have a `make` task that will create a docker image for you locally to start.
```suggestion
If not, you could create containers to deploy your workload clusters on. We have a `make` task that will create a docker image for you locally to start. 
```

2021-11-12 07:52 UTC, pshail requested changes
Minor nits post that LGTM

2021-11-12 07:52 UTC, pshail commented on docs/getting_started.md
> +This is a guide on how to get started with Cluster API Provider BringYourOwnHost(BYOH). To learn more about Cluster API in more depth, check out the the [Cluster API book][cluster-api-book].
Nit: 
```suggestion
This is a guide on how to get started with Cluster API Provider BringYourOwnHost(BYOH). To learn more about Cluster API in more depth, check out the [Cluster API book][cluster-api-book].
```

2021-11-12 07:52 UTC, pshail commented on docs/getting_started.md
> +If not, you could create containers to deploy you workload clusters on. We have a `make` task that will create a docker image for you locally to start.
```suggestion
If not, you could create containers to deploy your workload clusters on. We have a `make` task that will create a docker image locally for you to start.
```

2021-11-12 07:52 UTC, pshail commented on docs/getting_started.md
> +Assuming you have downloaded the `byoh-hostagent-linux-amd64` into your working directory, you can use use the following script to start the agent on the containers.
```suggestion
Assuming you have downloaded the `byoh-hostagent-linux-amd64` into your working directory, you can use the following script to start the agent on the containers.
```

2021-11-15 03:55 UTC, anusha94 approved these changes
LGTM. Thank you for updating the ~~README~~ getting-started docs 🙂

2021-11-15 06:45 UTC, pshail commented
LGTM

2021-11-15 06:46 UTC, pshail approved these changes

2021-11-15 07:49 UTC, shamsher31 approved these changes

2021-11-15 07:52 UTC, merged